/**
 * @packageDocumentation
 * @module api.functional.codes
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { CodeRow } from "../../../../../apps/api/domain/entities/code";
import type { Primitive } from "typia";

import type { CreateCodeDto } from "../../../../../apps/api/src/codes/dto/create-code.dto";

/**
 * @controller CodesController.create
 * @path POST /codes
 * @accessor api.functional.codes.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreateCodeDto>;
  export type Output = Primitive<CodeRow>;

  export const METADATA = {
    method: "POST",
    path: "/codes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/codes";
}

/**
 * @controller CodesController._delete
 * @path DELETE /codes/:id
 * @accessor api.functional.codes._delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function _delete(
  connection: IConnection,
  id: string,
): Promise<_delete.Output> {
  return PlainFetcher.fetch(connection, {
    ..._delete.METADATA,
    template: _delete.METADATA.path,
    path: _delete.path(id),
  });
}
export namespace _delete {
  export type Output = Primitive<CodeRow>;

  export const METADATA = {
    method: "DELETE",
    path: "/codes/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/codes/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller CodesController.list
 * @path GET /codes
 * @accessor api.functional.codes.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(connection: IConnection): Promise<list.Output> {
  return PlainFetcher.fetch(connection, {
    ...list.METADATA,
    template: list.METADATA.path,
    path: list.path(),
  });
}
export namespace list {
  export type Output = Primitive<Array<CodeRow>>;

  export const METADATA = {
    method: "GET",
    path: "/codes",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/codes";
}
