/**
 * @packageDocumentation
 * @module api.functional.commandes.status
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { CommandeRow } from "../../../../../../apps/api/domain/entities/commandes";
import type { UpdateCommandeStatusDto } from "../../../../../../apps/api/src/commandes/dto/update-commande-status.dto";

/**
 * @controller CommandesController.updateStatus
 * @path PATCH /commandes/:id/status
 * @accessor api.functional.commandes.status.updateStatus
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateStatus(
  connection: IConnection,
  id: string,
  dto: updateStatus.Body,
): Promise<updateStatus.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateStatus.METADATA,
      template: updateStatus.METADATA.path,
      path: updateStatus.path(id),
    },
    dto,
  );
}
export namespace updateStatus {
  export type Body = Primitive<UpdateCommandeStatusDto>;
  export type Output = Primitive<CommandeRow>;

  export const METADATA = {
    method: "PATCH",
    path: "/commandes/:id/status",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/commandes/${encodeURIComponent(id?.toString() ?? "null")}/status`;
}
