import type { Metadata } from "next";
import "./globals.css";
import { monoton, cinzel, playfair } from "./font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${monoton.variable} ${cinzel.variable} ${playfair.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
