/**
 * @packageDocumentation
 * @module api.functional.ingredients.in_stock
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { IngredientRow } from "../../../../../../apps/api/domain/entities/ingredients";
import type { Primitive } from "typia";

/**
 * @controller IngredientsController.inStock
 * @path PATCH /ingredients/:id/in-stock
 * @accessor api.functional.ingredients.in_stock.inStock
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function inStock(
  connection: IConnection,
  id: string,
): Promise<inStock.Output> {
  return PlainFetcher.fetch(connection, {
    ...inStock.METADATA,
    template: inStock.METADATA.path,
    path: inStock.path(id),
  });
}
export namespace inStock {
  export type Output = Primitive<IngredientRow>;

  export const METADATA = {
    method: "PATCH",
    path: "/ingredients/:id/in-stock",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/ingredients/${encodeURIComponent(id?.toString() ?? "null")}/in-stock`;
}
