/**
 * @packageDocumentation
 * @module api.functional.ingredients
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { IngredientRow } from "../../../../../apps/api/domain/entities/ingredients";
import type { Primitive } from "typia";

import type { CreateIngredientDto } from "../../../../../apps/api/src/ingredients/dto/create-ingredient.dto";
import type { UpdateIngredientDto } from "../../../../../apps/api/src/ingredients/dto/update-ingredient.dto";

export * as in_stock from "./in_stock/index";
export * as out_of_stock from "./out_of_stock/index";

/**
 * @controller IngredientsController.list
 * @path GET /ingredients
 * @accessor api.functional.ingredients.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(connection: IConnection): Promise<list.Output> {
  return PlainFetcher.fetch(connection, {
    ...list.METADATA,
    template: list.METADATA.path,
    path: list.path(),
  });
}
export namespace list {
  export type Output = Primitive<Array<IngredientRow>>;

  export const METADATA = {
    method: "GET",
    path: "/ingredients",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/ingredients";
}

/**
 * @controller IngredientsController.getById
 * @path GET /ingredients/:id
 * @accessor api.functional.ingredients.getById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: string,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = Primitive<IngredientRow>;

  export const METADATA = {
    method: "GET",
    path: "/ingredients/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/ingredients/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller IngredientsController.create
 * @path POST /ingredients
 * @accessor api.functional.ingredients.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreateIngredientDto>;
  export type Output = Primitive<IngredientRow>;

  export const METADATA = {
    method: "POST",
    path: "/ingredients",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/ingredients";
}

/**
 * @controller IngredientsController.update
 * @path PATCH /ingredients/:id
 * @accessor api.functional.ingredients.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  dto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    dto,
  );
}
export namespace update {
  export type Body = Primitive<UpdateIngredientDto>;
  export type Output = Primitive<IngredientRow>;

  export const METADATA = {
    method: "PATCH",
    path: "/ingredients/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/ingredients/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller IngredientsController._delete
 * @path DELETE /ingredients/:id
 * @accessor api.functional.ingredients._delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function _delete(
  connection: IConnection,
  id: string,
): Promise<_delete.Output> {
  return PlainFetcher.fetch(connection, {
    ..._delete.METADATA,
    template: _delete.METADATA.path,
    path: _delete.path(id),
  });
}
export namespace _delete {
  export type Output = Primitive<IngredientRow>;

  export const METADATA = {
    method: "DELETE",
    path: "/ingredients/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/ingredients/${encodeURIComponent(id?.toString() ?? "null")}`;
}
