/**
 * @packageDocumentation
 * @module api.functional.ingredients.out_of_stock
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { IngredientRow } from "../../../../../../apps/api/domain/entities/ingredients";
import type { Primitive } from "typia";

/**
 * @controller IngredientsController.outOfStock
 * @path PATCH /ingredients/:id/out-of-stock
 * @accessor api.functional.ingredients.out_of_stock.outOfStock
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function outOfStock(
  connection: IConnection,
  id: string,
): Promise<outOfStock.Output> {
  return PlainFetcher.fetch(connection, {
    ...outOfStock.METADATA,
    template: outOfStock.METADATA.path,
    path: outOfStock.path(id),
  });
}
export namespace outOfStock {
  export type Output = Primitive<IngredientRow>;

  export const METADATA = {
    method: "PATCH",
    path: "/ingredients/:id/out-of-stock",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/ingredients/${encodeURIComponent(id?.toString() ?? "null")}/out-of-stock`;
}
