/**
 * @packageDocumentation
 * @module api.functional.commandes._public
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { CommandeView } from "../../../../../../apps/api/domain/entities/commande";

/**
 * @controller CommandesController.getByPublicToken
 * @path GET /commandes/public/:token
 * @accessor api.functional.commandes._public.getByPublicToken
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByPublicToken(
  connection: IConnection,
  token: string,
): Promise<getByPublicToken.Output> {
  return PlainFetcher.fetch(connection, {
    ...getByPublicToken.METADATA,
    template: getByPublicToken.METADATA.path,
    path: getByPublicToken.path(token),
  });
}
export namespace getByPublicToken {
  export type Output = Primitive<CommandeView>;

  export const METADATA = {
    method: "GET",
    path: "/commandes/public/:token",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (token: string) =>
    `/commandes/public/${encodeURIComponent(token?.toString() ?? "null")}`;
}
