/**
 * @packageDocumentation
 * @module api.functional.cocktails.ingredients
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type {
  CocktailIngredientLinkRow,
  CocktailIngredientListItem,
  DeleteMessage,
} from "../../../../../../apps/api/domain/entities/cocktails";
import type { AddCocktailIngredientDto } from "../../../../../../apps/api/src/cocktails/dto/add-cocktail-ingredient.dto";
import type { UpdateCocktailIngredientDto } from "../../../../../../apps/api/src/cocktails/dto/update-cocktail-ingredient.dto";

/**
 * @controller CocktailsController.getCocktailIngredients
 * @path GET /cocktails/:cocktailId/ingredients
 * @accessor api.functional.cocktails.ingredients.getCocktailIngredients
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getCocktailIngredients(
  connection: IConnection,
  cocktailId: string,
): Promise<getCocktailIngredients.Output> {
  return PlainFetcher.fetch(connection, {
    ...getCocktailIngredients.METADATA,
    template: getCocktailIngredients.METADATA.path,
    path: getCocktailIngredients.path(cocktailId),
  });
}
export namespace getCocktailIngredients {
  export type Output = Primitive<Array<CocktailIngredientListItem>>;

  export const METADATA = {
    method: "GET",
    path: "/cocktails/:cocktailId/ingredients",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (cocktailId: string) =>
    `/cocktails/${encodeURIComponent(cocktailId?.toString() ?? "null")}/ingredients`;
}

/**
 * @controller CocktailsController.addIngredient
 * @path POST /cocktails/:cocktailId/ingredients
 * @accessor api.functional.cocktails.ingredients.addIngredient
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function addIngredient(
  connection: IConnection,
  cocktailId: string,
  dto: addIngredient.Body,
): Promise<addIngredient.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...addIngredient.METADATA,
      template: addIngredient.METADATA.path,
      path: addIngredient.path(cocktailId),
    },
    dto,
  );
}
export namespace addIngredient {
  export type Body = Primitive<AddCocktailIngredientDto>;
  export type Output = Primitive<CocktailIngredientLinkRow>;

  export const METADATA = {
    method: "POST",
    path: "/cocktails/:cocktailId/ingredients",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (cocktailId: string) =>
    `/cocktails/${encodeURIComponent(cocktailId?.toString() ?? "null")}/ingredients`;
}

/**
 * @controller CocktailsController.updateIngredient
 * @path PATCH /cocktails/:cocktailId/ingredients/:cocktailIngredientId
 * @accessor api.functional.cocktails.ingredients.updateIngredient
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateIngredient(
  connection: IConnection,
  cocktailId: string,
  cocktailIngredientId: string,
  dto: updateIngredient.Body,
): Promise<updateIngredient.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateIngredient.METADATA,
      template: updateIngredient.METADATA.path,
      path: updateIngredient.path(cocktailId, cocktailIngredientId),
    },
    dto,
  );
}
export namespace updateIngredient {
  export type Body = Primitive<UpdateCocktailIngredientDto>;
  export type Output = Primitive<CocktailIngredientLinkRow>;

  export const METADATA = {
    method: "PATCH",
    path: "/cocktails/:cocktailId/ingredients/:cocktailIngredientId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (cocktailId: string, cocktailIngredientId: string) =>
    `/cocktails/${encodeURIComponent(cocktailId?.toString() ?? "null")}/ingredients/${encodeURIComponent(cocktailIngredientId?.toString() ?? "null")}`;
}

/**
 * @controller CocktailsController.deleteIngredient
 * @path DELETE /cocktails/:cocktailId/ingredients/:cocktailIngredientId
 * @accessor api.functional.cocktails.ingredients.deleteIngredient
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteIngredient(
  connection: IConnection,
  cocktailId: string,
  cocktailIngredientId: string,
): Promise<deleteIngredient.Output> {
  return PlainFetcher.fetch(connection, {
    ...deleteIngredient.METADATA,
    template: deleteIngredient.METADATA.path,
    path: deleteIngredient.path(cocktailId, cocktailIngredientId),
  });
}
export namespace deleteIngredient {
  export type Output = Primitive<DeleteMessage>;

  export const METADATA = {
    method: "DELETE",
    path: "/cocktails/:cocktailId/ingredients/:cocktailIngredientId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (cocktailId: string, cocktailIngredientId: string) =>
    `/cocktails/${encodeURIComponent(cocktailId?.toString() ?? "null")}/ingredients/${encodeURIComponent(cocktailIngredientId?.toString() ?? "null")}`;
}
