/**
 * @packageDocumentation
 * @module api.functional.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { LoginResponse } from "../../../../../apps/api/domain/entities/auth";
import type { LoginDto } from "../../../../../apps/api/src/auth/dto/login.dto";

/**
 * @controller AuthController.login
 * @path POST /auth/login
 * @accessor api.functional.auth.login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  dto: login.Body,
): Promise<login.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...login.METADATA,
      template: login.METADATA.path,
      path: login.path(),
    },
    dto,
  );
}
export namespace login {
  export type Body = Primitive<LoginDto>;
  export type Output = Primitive<LoginResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/login";
}
