/**
 * @packageDocumentation
 * @module api.functional.commandes
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type {
  CommandeRow,
  CommandeView,
} from "../../../../../apps/api/domain/entities/commandes";
import type { CreateCommandeDto } from "../../../../../apps/api/src/commandes/dto/create-commande.dto";

export * as _public from "./_public/index";
export * as status from "./status/index";

/**
 * @controller CommandesController.create
 * @path POST /commandes
 * @accessor api.functional.commandes.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreateCommandeDto>;
  export type Output = Primitive<CommandeView>;

  export const METADATA = {
    method: "POST",
    path: "/commandes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/commandes";
}

/**
 * @controller CommandesController.listAll
 * @path GET /commandes
 * @accessor api.functional.commandes.listAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listAll(
  connection: IConnection,
): Promise<listAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...listAll.METADATA,
    template: listAll.METADATA.path,
    path: listAll.path(),
  });
}
export namespace listAll {
  export type Output = Primitive<Array<CommandeRow>>;

  export const METADATA = {
    method: "GET",
    path: "/commandes",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/commandes";
}

/**
 * @controller CommandesController.getById
 * @path GET /commandes/:id
 * @accessor api.functional.commandes.getById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: string,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = Primitive<CommandeView>;

  export const METADATA = {
    method: "GET",
    path: "/commandes/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/commandes/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller CommandesController._delete
 * @path DELETE /commandes/:id
 * @accessor api.functional.commandes._delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function _delete(
  connection: IConnection,
  id: string,
): Promise<_delete.Output> {
  return PlainFetcher.fetch(connection, {
    ..._delete.METADATA,
    template: _delete.METADATA.path,
    path: _delete.path(id),
  });
}
export namespace _delete {
  export type Output = Primitive<{ message: string }>;

  export const METADATA = {
    method: "DELETE",
    path: "/commandes/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/commandes/${encodeURIComponent(id?.toString() ?? "null")}`;
}
