/**
 * @packageDocumentation
 * @module api.functional.cocktails
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { FormDataInput, IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type {
  CocktailRow,
  CocktailView,
} from "../../../../../apps/api/domain/entities/cocktails";
import type {
  CreateCocktailFormData,
  UpdateCocktailFormData,
} from "../../../../../apps/api/src/cocktails/cocktails.form-types";

export * as ingredients from "./ingredients/index";

/**
 * @controller CocktailsController.list
 * @path GET /cocktails
 * @accessor api.functional.cocktails.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(connection: IConnection): Promise<list.Output> {
  return PlainFetcher.fetch(connection, {
    ...list.METADATA,
    template: list.METADATA.path,
    path: list.path(),
  });
}
export namespace list {
  export type Output = Primitive<Array<CocktailRow>>;

  export const METADATA = {
    method: "GET",
    path: "/cocktails",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/cocktails";
}

/**
 * @controller CocktailsController.getById
 * @path GET /cocktails/:id
 * @accessor api.functional.cocktails.getById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: string,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = Primitive<CocktailView>;

  export const METADATA = {
    method: "GET",
    path: "/cocktails/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/cocktails/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller CocktailsController.create
 * @path POST /cocktails
 * @accessor api.functional.cocktails.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  input: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    connection,
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    input,
  );
}
export namespace create {
  export type Body = FormDataInput<CreateCocktailFormData>;
  export type Output = Primitive<CocktailRow>;

  export const METADATA = {
    method: "POST",
    path: "/cocktails",
    request: {
      type: "multipart/form-data",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/cocktails";
}

/**
 * @controller CocktailsController.update
 * @path PATCH /cocktails/:id
 * @accessor api.functional.cocktails.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  input: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    connection,
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    input,
  );
}
export namespace update {
  export type Body = FormDataInput<UpdateCocktailFormData>;
  export type Output = Primitive<CocktailRow>;

  export const METADATA = {
    method: "PATCH",
    path: "/cocktails/:id",
    request: {
      type: "multipart/form-data",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/cocktails/${encodeURIComponent(id?.toString() ?? "null")}`;
}
